import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import Link from "next/link";
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuList,
} from "@/components/ui/navigation-menu";

import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { BellIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import NotificationList from "@/components/NotificationList";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div>
      <NavigationMenu className="p-5 shadow-lg mx-auto ">
        <NavigationMenuList className="flex space-x-4">
          <NavigationMenuItem>
            <Link
              href="/"
              className="px-4 py-2 text-white hover:bg-gray-700 rounded transition duration-300"
            >
              Home
            </Link>
          </NavigationMenuItem>
          <NavigationMenuItem>
            <Link
              href="/search"
              className="px-4 py-2 text-white hover:bg-gray-700 rounded transition duration-300"
            >
              Search
            </Link>
          </NavigationMenuItem>
          <NavigationMenuItem>
            <Link
              href="/items/addItem"
              className="px-4 py-2 text-white hover:bg-gray-700 rounded transition duration-300"
            >
              Add Item
            </Link>
          </NavigationMenuItem>
          {/* <NavigationMenuItem>
              <Link
                href="/lost-items"
                className="px-4 py-2 text-white hover:bg-gray-700 rounded transition duration-300"
              >
                Lost Items
              </Link>
            </NavigationMenuItem> */}
          {/* <NavigationMenuItem>
              <Link
                href="/found-items"
                className="px-4 py-2 text-white hover:bg-gray-700 rounded transition duration-300"
              >
                Found Items
              </Link>
            </NavigationMenuItem> */}
          <NavigationMenuItem>
            <Popover>
              <PopoverTrigger asChild>
                <Button variant="outline">
                  <BellIcon />
                  Notifications
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-200">
                <NotificationList />
              </PopoverContent>
            </Popover>
          </NavigationMenuItem>

          <NavigationMenuItem>
            <Link
              href="/signout"
              className="px-4 py-2 text-red-500 bg-gray-700 rounded transition duration-300"
            >
              Sign Out
            </Link>
          </NavigationMenuItem>
        </NavigationMenuList>
      </NavigationMenu>
      <main>{children}</main>
      <Toaster />
    </div>
  );
}
